### ISSUE TITLE
Will `postalService` contract ever go live?

### ISSUE THREAD

**Issue by anilhelvaci** [agoric-labs/ag-power-tools#29]
## Question
I am exploring options for sending an array of invitations to a set of whitelisted accounts in a transaction governed by EC. The objective (I believe) is to have the operation complete without any BLDer DAO intervention so I'm discounting options that use a core-eval to send invitations. The `postalService` contract hit me when I remembered our discussions in the Office Hours. So I'm wondering is there any chance I can count on `postalService` contract for this task? @dckc

**Comment by dckc** [comment]
_if you don't find this answer suffcient, feel free to re-open the issue._

I'm not aware of any concrete plans to launch `postalService` on mainnet. I'm not aware of any particular obstacles to launching it (after suitable review / refinement), either. We expect to have regular upgrades to address minor issues as well as major issues, so if there's a good reason to launch it, it seems feasible.

OTOH, it's not particularly novel / powerful. Any feature that could be done by invoking the postalService could be done just by using `namesByAddress` (or `namesByAddressAdmin` if the fix for https://github.com/Agoric/agoric-sdk/issues/8113 isn't on mainnet yet.)

Note that postalService is maintained as part of an example dapp now, unlike this un-maintained `agoric-labs` playground:

https://github.com/Agoric/dapp-agoric-basics/blob/main/contract/src/postal-service.contract.js

cc @mitdralla

**Comment by anilhelvaci** [comment]
Hey @dckc - Thanks for clarifying. I could use some suggestions on where to leverage `depositFacet` makes the most sense in terms positioning the authority. So looking forward to talking about this in the office hours!
